#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

apt update
apt upgrade -y
apt -y install ntp bind9 curl jq nload

service ntp restart
#service ntp status
sed -i -r 's/listen-on-v6/listen-on/g'  /etc/bind/named.conf.options 
sed -i '/listen-on/a \\tallow-query { any; };'  /etc/bind/named.conf.options 
apt -y  install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

apt update
apt install  -y docker-ce snapd make dialog nmap  bash-completion
#systemctl status docker
#curl -sL https://talos.dev/install | sh

releases=$(curl -s https://api.github.com/repos/siderolabs/talos/releases | jq -r '.[].tag_name' | head -n 10)
echo -e "${YELLOW}Выберите версию talos клиента для скачивания:${NC}"
select version in $releases; do
    if [[ -n "$version" ]]; then
        echo "Вы выбрали версию $version"
        break
    else
        echo -e "${RED}Неверный выбор. Пожалуйста, попробуйте еще раз. ${NC}"
    fi
done
url="https://github.com/siderolabs/talos/releases/download/$version/talosctl-linux-amd64"
wget $url -O talosctl
chmod +x talosctl
sudo mv talosctl /usr/local/bin/
#kubectl
releases=$(curl -s https://api.github.com/repos/kubernetes/kubernetes/releases | jq -r '.[].tag_name' | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | head -n 10)
echo -e "${YELLOW}Выберите версию kubectl для скачивания:${NC}"
select version in $releases; do
    if [[ -n "$version" ]]; then
        echo  "Вы выбрали версию $version"
        break
    else
        echo -e "${RED}Неверный выбор. Пожалуйста, попробуйте еще раз. ${NC}"
    fi
done
url="https://storage.googleapis.com/kubernetes-release/release/$version/bin/linux/amd64/kubectl"
wget $url -O kubectl
chmod +x kubectl
sudo mv kubectl /usr/local/bin/

# Получаем список доступных версий Helm через GitHub API
echo "Получаем список доступных версий Helm..."
versions=$(curl -s https://api.github.com/repos/helm/helm/releases | grep -Po '"tag_name": "\Kv[0-9]+\.[0-9]+\.[0-9]+' | head -n 10)

# Проверяем, удалось ли получить список версий
if [ -z "$versions" ]; then
  echo "Не удалось получить список версий."
  exit 1
fi

# Выводим версии и предлагаем выбор
echo "Доступные версии Helm:"
select version in $versions; do
  [[ -n "$version" ]] && break
  echo "Некорректный выбор. Попробуйте снова."
done

# Формируем ссылку на скачивание скрипта для выбранной версии
echo "Скачиваем и устанавливаем Helm версии $version..."
curl -fsSL -o get_helm.sh "https://raw.githubusercontent.com/helm/helm/${version}/scripts/get-helm-3"
chmod 700 get_helm.sh
./get_helm.sh

# Проверяем успешную установку Helm
if command -v helm &> /dev/null; then
    echo "Helm версии $version успешно установлен!"
    helm version
else
    echo "Ошибка установки Helm."
fi

curl -LO https://github.com/kvaps/kubectl-node-shell/raw/master/kubectl-node_shell
chmod +x ./kubectl-node_shell
sudo mv ./kubectl-node_shell /usr/local/bin/kubectl-node_shell

# Получаем список версий с помощью GitHub API и выводим их
echo "Получаем список доступных версий talm"
versions=$(curl -s https://api.github.com/repos/aenix-io/talm/releases | grep -Po '"tag_name": "\K[^"]+')

# Если список версий пустой, выводим ошибку и выходим
[[ -z "$versions" ]] && { echo "Не удалось получить список версий."; exit 1; }

# Выводим версии и предлагаем выбор
echo "Доступные версии:"
select version in $versions; do
  [[ -n "$version" ]] && break
  echo "Некорректный выбор. Попробуйте снова."
done

# Формируем ссылку на скачивание
download_url="https://github.com/aenix-io/talm/releases/download/$version/talm-linux-amd64"

# Скачиваем и устанавливаем выбранную версию
echo "Скачиваем talm версии $version..."
curl -LO $download_url && chmod +x talm-linux-amd64 && sudo mv talm-linux-amd64 /usr/local/bin/talm

# Проверяем успешность установки
echo "Проверка установки..."
talm --version && echo "talm успешно установлен!" || echo "Ошибка установки."

echo "Укажите название директории для конфигурационных файлов,"
echo -e "директория будет располагаться в каталоге ${GREEN}/opt/${NC}. По умолчанию: ${GREEN}/opt/cozystack${NC}"
echo -e "${YELLOW}"
read -p "Введите название директории: " cozystack
echo -e "${NC}"
if [ -z "$cozystack" ]; then    
  cozystack="cozystack" 
fi
mkdir -p /opt/$cozystack
curl -LO https://github.com/aenix-io/talos-bootstrap/raw/master/talos-bootstrap
mv talos-bootstrap /opt/$cozystack
chmod +x /opt/$cozystack/talos-bootstrap
snap install  yq
echo -e "${YELLOW}Укажите IP-сеть для  etcd и kubelet${NC}"
echo -e "По умолчанию: ${GREEN} 192.168.100.0/24 ${NC}"
read -p "IP-сеть (network/mask): " IPEK 
if [ -z "$IPEK" ]; then    
  IPEK="192.168.100.0/24" 
fi
#ADD FORWARD (RELATED,ESTABLISHED)
rule1="-d $IPEK -m state --state RELATED,ESTABLISHED -m comment --comment $cozystack -j ACCEPT"
if ! iptables-save | grep -q -- "-A FORWARD $rule1"; then
    iptables -I FORWARD -d $IPEK -m state --state RELATED,ESTABLISHED -m comment --comment $cozystack -j ACCEPT
fi
# ADD FORWARD
rule2="-s $IPEK -m comment --comment $cozystack -j ACCEPT"
if ! iptables-save | grep -q -- "-A FORWARD $rule2"; then
    iptables -I FORWARD -s $IPEK -m comment --comment $cozystack -j ACCEPT
fi
# ADD NAT
rule3="-s $IPEK -m comment --comment $cozystack -j MASQUERADE"
if ! iptables-save | grep -q -- "-A POSTROUTING $rule3"; then
    iptables -t nat -I POSTROUTING -s $IPEK -m comment --comment $cozystack -j MASQUERADE
fi
#sysctl -w net.ipv4.ip_forward=1
if ! grep -qF "$REQUIRED_SETTING" "$FILE"; then
  echo "net.ipv4.ip_forward = 1" | sudo tee -a "/etc/sysctl.conf" > /dev/null 
fi
sysctl -p
apt -y install iptables-persistent 

url="https://cozystack.io/docs/talos/configuration/talos-bootstrap/"
TALOSV=$(curl -s "$url" | grep -oP 'ghcr\.io/aenix-io/cozystack/talos:\K[^<]+')

cat > /opt/$cozystack/patch.yaml <<EOT
machine:
  kubelet:
    nodeIP:
      validSubnets:
      - $IPEK
    extraConfig:
      maxPods: 512
  kernel:
    modules:
    - name: openvswitch
    - name: drbd
      parameters:
        - usermode_helper=disabled
    - name: zfs
    - name: spl
  install:
    image: ghcr.io/aenix-io/cozystack/talos:$TALOSV
  files:
  - content: |
      [plugins]
        [plugins."io.containerd.grpc.v1.cri"]
          device_ownership_from_security_context = true      
    path: /etc/cri/conf.d/20-customization.part
    op: create
cluster:
  network:
    cni:
      name: none
    dnsDomain: cozy.local
    podSubnets:
    - 10.244.0.0/16
    serviceSubnets:
    - 10.96.0.0/16
EOT

cat > /opt/$cozystack/patch-controlplane.yaml <<EOT
cluster:
  allowSchedulingOnControlPlanes: true
  controllerManager:
    extraArgs:
      bind-address: 0.0.0.0
  scheduler:
    extraArgs:
      bind-address: 0.0.0.0
  apiServer:
    certSANs:
    - 127.0.0.1
  proxy:
    disabled: true
  discovery:
    enabled: false
  etcd:
    advertisedSubnets:
    - $IPEK
EOT
### Install k9s
curl -sS https://webinstall.dev/k9s | bash
echo "talm       in folder" $(which  talm)
### hot key k
#echo 'alias k=kubectl' >> ~/.bashrc
#echo 'source <(kubectl completion bash)' >>  ~/.bashrc
#echo 'complete -o default -F __start_kubectl k' >>  ~/.bashrc

 
echo 'source <(kubectl completion bash)' >> ~/.bashrc
echo 'source /usr/share/bash-completion/bash_completion' >> ~/.bashrc
echo 'alias k=kubectl' >> ~/.bashrc
echo 'complete -o default -F __start_kubectl k' >> ~/.bashrc
source ~/.bashrc

echo -e "${YELLOW}========== Installed binary ===========${NC}"
echo "helm       in folder" $(which helm)
echo "yq         in folder" $(which yq)
echo "kubectl    in folder" $(which kubectl)
echo "docker     in folder" $(which  docker)
echo "talosctl   in folder" $(which  talosctl)
echo "dialog     in folder" $(which  dialog)
echo "nmap       in folder" $(which  nmap)
echo "talm       in folder" $(which  talm)
echo "k9s       in folder" $(which  k9s)
echo "node_shell       in folder" $(which  kubectl-node_shell)
echo -e "${YELLOW}========== services runing ===========${NC}"
echo -ne "DNS Bind9       ${GREEN}"; systemctl is-active bind9 
echo -en "${NC}"
echo -n -e "NTP             ${GREEN}"; systemctl is-active ntp 
echo -en "${NC}"
echo -e "${YELLOW}========== ADD Iptables Rule ===========${NC}"
iptables -S | grep $cozystack
iptables -t nat -S | grep $cozystack
echo -e "${RED}!!!  Please change the catalog to work with talos-bootstrap !!!${NC}"
echo -e "${GREEN}cd  /opt/$cozystack ${NC}"
